### ISSUE TITLE
pgexporter produces incorrect output

### ISSUE THREAD

**Issue by nikitabugrovsky** [pgexporter/pgexporter#71]
**Describe the bug**

Prometheus server & SignalFX fails to parse the following line:

```
#HELP pgexporter_pg_settings_backslash_quote Sets whether "\'" is allowed in string literals
```

**To Reproduce**

```
curl http://localhost:5002/metrics
```
See the offending line in the output.

**Version**

pgexporter 0.3.2

**PostgreSQL**

PostgreSQL 15

**OS**

RHEL 8

**Configuration**

No custom queries yaml file is provided as part of the configuration.  pgexporter.conf & pgexporter_users.conf are provided only.

**Comment by jesperpedersen** [comment]
@resyfer Can you take a look at this ?

**Comment by resyfer** [comment]
I'll take a look at it tomorrow early morning. Luckily I had just very recently setup both Prometheus and Grafana for pgexporter on my local machine with quite a lot of help from Zhengshun on this, so I can test it there as well to check the problem.

**Comment by resyfer** [comment]
I looked into it. The output seems to be correct:
![image](https://github.com/pgexporter/pgexporter/assets/74897008/09586ad4-64cb-4b84-86be-87e4c67fb7e4)
![image](https://github.com/pgexporter/pgexporter/assets/74897008/808961f4-2d3c-421a-b46c-bc903777799a)

I tried using both Prometheus server and Grafana (just to check), and while I have not been able to find a query that gets me the `#HELP` of a metric, the metrics exposed by the collector are parsed properly by both:
![image](https://github.com/pgexporter/pgexporter/assets/74897008/170a1042-912b-4024-b95d-376e5da5056c)
![image](https://github.com/pgexporter/pgexporter/assets/74897008/60074a87-f0b3-4da0-bc5c-be6a09f43a79)

(it would have given a parse error if it couldn't parse it)

I've yet to try SignalFX. I think the issue lies with SignalFX, pretty similar to this [issue](https://github.com/grafana/grafana/issues/24478) due to the `\`.

**Comment by nikitabugrovsky** [comment]
I can confirm that the buggy behavior can be attributed to [otel collector prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/simpleprometheusreceiver) only.

The prometheus server parses the line correctly.

Specific error I am getting from otel prometheus receiver 
```
line 1656: invalid escape sequence '\\''", "monitorID": "smartagentprometheusexporter", "monitorType": "prometheus-exporter"
```

**Comment by nikitabugrovsky** [comment]
@resyfer Great observation.
Looks like pgexporter is compliant with [the prometheus exposition formats](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#text-format-details) & fix is expected from  otel collector.
